k

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,7 +28,47 @@ jobs:
         working-directory: ./sub_container
         run: docker build --build-arg host_group_name=conti --rm -t subscriber-image .
 
-      - name: Test1 Publisher- und Subscriber-Container with same Hostname
+      - name: Test Communication on same and different Hostname for same host_group_name
+        run: |
+          tests=(
+            "host1"
+            "host"
+          )
+
+          for test in "${tests[@]}"; do
+            echo "Running test with hostname: $test"
+            docker run --rm -d --name publisher-container --ipc=host --network=host --pid=host -h=host1 publisher-image
+            docker run --rm -d --name subscriber-container --ipc=host --network=host --pid=host -h=$test subscriber-image
+            sleep 3
+            logs=$(docker logs subscriber-container)
+            if [[ -n "$logs" ]]; then
+              if [[ "$test" == "host1" ]]; then
+                echo "Test passed: Messages received in logs"
+              else
+                echo "Test failed: Unexpected messages found in logs"
+                exit 1
+              fi
+            else
+              if [[ "$test" == "host1" ]]; then
+                echo "Test failed: No messages found in logs"
+                exit 1
+              else
+                echo "Test passed: No messages expected"
+              fi
+            fi
+            docker stop publisher-container
+            docker stop subscriber-container
+          done
+
+      - name: Prepare Publisher for Host-Group-Name-Test
+        working-directory: ./pub_container
+        run: docker build --build-arg host_group_name=continental --rm -t publisher-image .
+
+      - name: Prepare Subscriber for Host-Group-Name-Test
+        working-directory: ./sub_container
+        run: docker build --build-arg host_group_name=conti --rm -t subscriber-image .
+
+      - name: Test different Host-Group-Names
         run: |
           docker run --rm -d --name publisher-container --ipc=host --network=host --pid=host -h=host1 publisher-image
           docker run --rm  -d --name subscriber-container --ipc=host --network=host --pid=host -h=host1 subscriber-image
@@ -36,37 +76,7 @@ jobs:
           logs=$(docker logs subscriber-container)
           if [[ -n "$logs" ]]; then
             echo "Test1 passed: Messages received in logs"
-            echo "Ping will be send"
-            #docker run -d -it --name ecal-runtime --ipc=host --network=host --pid=host -h=host1 ecal-runtime
-            #sleep 3
-            #docker exec ecal-runtime ping -c 2 publisher-container
-            #docker exec ecal-runtime ping -c 2 subscriber-container
           else
             echo "Test1 failed: No messages found in logs"
             exit 1
           fi
-          
-
-      - name: Stop Containers
-        run: |
-          docker stop publisher-container
-          docker stop subscriber-container
-          #docker stop ecal-runtime
-
-      - name: Test2 Different Hostname
-        run: |
-          docker run --rm -d --name publisher-container --ipc=host --network=host --pid=host -h=host1 publisher-image
-          docker run --rm  -d --name subscriber-container --ipc=host --network=host --pid=host -h=host subscriber-image
-          sleep 3
-          logs=$(docker logs subscriber-container)
-          if [[ -n "$logs" ]]; then
-            echo "Test2 failed: Communication was be able, but should not happen."
-            exit 1
-          else
-            echo "Test1 passed: No Communication"
-          fi
-
-      - name: Stop Containers
-        run: |
-          docker stop publisher-container
-          docker stop subscriber-container
